apiVersion: v1
kind: Service
metadata:
  name: project3-service
spec:
  selector:
    app: project3
  ports:
  - protocol: TCP
    port: 80           
    targetPort: 8080   
    nodePort: 31416    
  type: NodePort