apiVersion: v1
kind: Service
metadata:
  name: project3-service
  labels:
    app: project3
spec:
  selector:
    app: project3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31416
  type: NodePort
